wild_dbt_project:
  outputs:
    dev:
      type: duckdb
      path: './wild_dbt_project.duckdb'
      threads: 4
      keepalives_idle: 0
      search_path: main
    prod:
      type: duckdb
      path: './wild_dbt_project_prod.duckdb'
      threads: 4
      keepalives_idle: 0
      search_path: main
  target: dev